
const ALERT ='ALERT'
const REFETCH_CHAT = 'REFETCH_CHAT'

const NEW_ATTACHEMENT = 'NEW_ATTACHEMENT'
const NEW_MESSAGE = 'NEW_MESSAGE'


const NEW_REQUEST = 'NEW_REQUEST'
export { ALERT, REFETCH_CHAT , NEW_ATTACHEMENT, NEW_MESSAGE, NEW_REQUEST} 